### ISSUE TITLE
AmpGen uses AVX512 when instructed to use AVX2

### ISSUE THREAD

**Issue by dcervenkov** [GooFit/AmpGen#22]
I'm having some issues running vectorized AmpGen on a batch farm with AVX2 capable machines. After some digging, it turns out that using the `-DUSE_SIMD=AVX2d` CMake argument results in an executable with AVX512 instructions (concretely the [vcvtusi2sd](https://software.intel.com/sites/landingpage/IntrinsicsGuide/#text=vcvtusi2sd) instruction).

Is this a bug? Is there some way to use only the AVX2d instructions?

**Comment by tevans1260** [comment]
The culprit is likely to be the -march=native in CMakeLists.txt (and that you are fortunate enough to have build machines with avx512 support). Should *probably* now be fixed in the master.

**Comment by dcervenkov** [comment]
Yes, it is now fixed in master. Thanks for the lightning-fast fix!

**Comment by dcervenkov** [comment]
One more cosmetic issue: When running AmpGen compiled with AVX512 it still shows avx2  on it's "splashscreen": `build: gcc 9.2.0 (avx2; double)  Jul  9 2021 12:09:57`.

**Comment by tevans1260** [comment]
Well spotted - thanks. 
A note of caution: I don't have any hardware to test the avx512 code on, so I haven't been able to test it so it will *probably* not work as expected. I'll adding a warning in the cmake.
